Added support for SHA256 checksums
FossilOrigin-Name: 8e05e7b5e2d1f70a01d20f0872332e0d472a3f72

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -29,7 +29,19 @@ function download () {
 	wget -O "${tmpfile}" "${url}" || return 1
 
 	if [ -n "${checksum}" ]; then
-		dl_checksum="$(openssl sha1 "${tmpfile}" 2>/dev/null | sed 's@.*= *@@')"
+		case "${checksum}" in
+			????????????????????????????????????????)
+				dl_checksum="$(openssl dgst -sha1 "${tmpfile}" 2>/dev/null | sed 's@.*= *@@')"
+				;;
+			????????????????????????????????????????????????????????????????)
+				dl_checksum="$(openssl dgst -sha256 "${tmpfile}" 2>/dev/null | sed 's@.*= *@@')"
+				;;
+			*)
+				echo "Invalid checksum value: ${checksum}" >&2
+
+				exit 1
+				;;
+		esac
 
 		if [ "${checksum}" != "${dl_checksum}" ]; then
 			echo "Checksum mismatch.  Got checksum: ${dl_checksum}; Expected checksum: ${checksum}" >&2
